version: '2'
services:
  starmaster:
    image: ericskang/starwood:master
    container_name: starmaster
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
      - "8088:8088"
      - "8188:8188"
      - "50070:50070"
    command: ["entrypoint.sh"]
  stardata0:
    image: ericskang/starwood:datanode
    container_name: stardata0
    ports:
      - "8081:8081"
    command: ["entrypoint.sh"]
  stardata1:
    image: ericskang/starwood:datanode
    container_name: stardata1
    ports:
      - "8082:8081"
    command: ["entrypoint.sh"]
  starui:
    image: ericskang/starwood:nginx
    container_name: starui
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]