version: '2'
services:
  starmaster:
    image: ericskang/starwood:master
    container_name: starmaster
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
      - "8088:8088"
    command: ["entrypoint.sh"]
  stardata0:
    image: ericskang/starwood:datanode
    container_name: stardata0
    ports:
      - "8081:8081"
    command: ["entrypoint.sh"]